name: sliver_app_bar_title
description: SliverAppBarTitle is a widget that can be used to show a title on pinned SliverAppBar based on scrolling and particular widget
version: 1.0.1+7
repository: https://github.com/itsmeabhi12/sliver_app_bar_title

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0





flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
